### ISSUE TITLE
Suggestion: use projected coordinate systems for output

### ISSUE THREAD

**Issue by DFEvans** [bunburya/bother#4]
Currently, the script outputs in WGS84, which leads to outputs being fairly "squashed" at higher latitudes (e.g. northern Europe). It'd be nice if it could output automatically in a relevant projected coordinate system - i.e. one with units of meters.

The UTM zones are a favourite of mine - they at least have predictable boundaries and cover the world, compared to country-specific projections like British National Grid. However, it's a bit of a pain working out which is best, especially when the area of interest extends over multiple zones - e.g. a map of the US would suffer from that problem, as it's so large, and it's almost certainly impossible to use a single UTM zone for something that big (the coordinate conversions eventually fails once you get too far out).

**Comment by DFEvans** [comment]
An alternative for the "squashing" issue could be to simply stretch the EPSG 4326 output - it's easier, if nothing else.

I've noticed that using an EPSG output other than 4326 results in nodata areas at the corners of the image after reprojection. This could be overcome, but coordinate manipulation and trying to work out the bounds you need to start from is a pain.

I'm also playing around with developing a script to populate real-life locations onto a height map, and having nice, square lat-lon bounds makes everything easier for converting to OTTD tile coordinates. That's especially true if the image is later cropped manually!

The approximate stretching required can be calculated from the average meters per degree of longitude and latitude across the image. For an example region (Germany) that's output as 11988x8641 pixels, the degrees-to-meters conversion gives a region of size 697x800km - so my image needed to be stretched vertically quite a bit, to give a horizontal:vertical ratio of 0.87. I therefore stretched in Y to 11988 / 0.87 = 13779 pixels, and then cropped square and scaled.

**Comment by bunburya** [comment]
Thanks for your thoughts on this.  WGS84 is what the CGIAR website gives us by default, which is why I just used that as the default and let the user specify their own projection to convert to using the `--epsg` flag - that seemed to me like the less "opinionated" option.  I take your point though that it doesn't make much sense to use WGS84 for a flat image, so the default option is unlikely to be very helpful for users.

My initial thought is to use Web Mercator as a default?  It is what most users are probably used to from using Google maps etc, and as I understand it, it can be used for any set of coordinates unlike a UTM zone.  I know Web Mercator has its critics as well but it would be very simple to implement as a default and because we only have SRTM data between 60° north and 56° south in any event, we won't be mapping the parts of the world where it starts to get it extremely wrong.  I'm kind of only learning about all these different projections though so happy to be corrected if I am talking nonsense.

I haven't noticed any NODATA values in my output reprojecting to Web Mercator, but I'll have to investigate that further.

**Comment by DFEvans** [comment]
> I haven't noticed any NODATA values in my output reprojecting to Web Mercator, but I'll have to investigate that further.

For Web Mercator it might not happen, as I presume that lines of latitude/longitude remain horizontal/vertical. Going to UTM 33N for Germany, you can see the slight curvature introduced by reprojecting leaves the corners out (not that you can really see at the top): ![image](https://user-images.githubusercontent.com/28623784/92325922-28bbe180-f046-11ea-8305-8e3992b6f7d6.png)

**Comment by bunburya** [comment]
Yep, that's quite clear.  The easiest way to "handle" it would be just to drop row/columns at the edges of the data that contain NODATA values, but you're potentially losing a lot of data there (which just means you'd need to use wider bounds).

This also points towards projecting to Web Mercator by default being a reasonable default; do you see any issues with that?

**Comment by DFEvans** [comment]
I did have a quick play with Web Mercator earlier, and it does handle the
"squashing" problem like you suggested - looks good! I think for placing
things on the heightmap, I'd need to do a bit more coordinate modification
to properly map - with a WGS84 projection, it's an easy mapping from
lat/lon to OTTD coordinates, but a little less trivial for Web Mercator.
