### ISSUE TITLE
Bother doesn't recognise when SRTM data is just sea and doesn't exist

### ISSUE THREAD

**Issue by aaannestad** [bunburya/bother#9]
The SRTM data set only has data for squares that include at least some land, but Bother doesn't realise this. When you attempt to generate a large heightmap that includes part of any ocean-only space not included in the SRTM data set, Bother attempts to access what _would_ be the URL for that square and gets a 404, and Python exits with an error. For example, if you try and create a height map including all of Vancouver Island and also Oregon, you'll get a 404 as Bother attempts to access the nonexistent tile south of Vancouver Island and west of Oregon. It's similarly impossible to get a map of all of the Hawai'ian islands.

This means that as things stand, if you're trying to make a large heightmap involving a significantly curved coastline, you simply cannot do it. It would likely be better to simply assume that any 404ed tile is empty ocean, with maybe a warning to the user that that might instead be caused by failure to connect.

**Comment by bunburya** [comment]
Thanks for flagging. For testing purposes, can you let me know the coordinates you were using?

**Comment by bunburya** [comment]
Thank you for flagging. I have merged a change which fixes this. I'm closing this issue but let me know if any further issues. Thanks!

**Comment by aaannestad** [comment]
Works perfectly now. Thank you!

**Comment by cnww-ns** [comment]
The solution introduces a new problem: Generating large heightmaps can now trigger many unnecessary fetch attempts **every time** because 404 results aren't cached.

For example I am presently trying to create a wide-aspect-ratio (rotated) map for a London to Tokyo OpenTTD scenario. This is an iterative process (no point in waiting for lake detection if I haven't got the bounding box right).

Currently, every time I re-build the output png with different command-line options, bother tries to download non-existent zip files for all the ocean squares, and the bounding-box selection method means that if I want both Japan and the UK in the same map, I must include large areas of the Atlantic and Pacific oceans, even though once I rotate and crop the output, those areas won't be in my final map.

Retrying after a timeout or an error 500 or 403 or the like is the correct behavior, but in topographical data an error 404 is usually permanent (barring major volcanic activity).

I would suggest that, if possible, you check the HTTP result code, and if it's an error 404, cache that result (either as an empty file or in a table) and avoid attempting to fetch that non-existent file again (possibly also provide instructions to the user on how to clear the cache if they think it was a temporary error).

In the meantime, I'm going to modify my setup to force bother to use a squid proxy so I can stop hammering the poor web server.
